const test = require('node:test');
const assert = require('node:assert/strict');
const { jsonLdBlocks, findRecipes, normalizeRecipe, RecipeCollector } = require('../lib/providers');
const { generatePlan, recalculatePlanShopping, FAMILY_PORTIONS } = require('../lib/planner');
const structured = `<script type="application/ld+json">{"@type":"Recipe","name":"Tarte aux courgettes","recipeYield":"4 portions","totalTime":"PT25M","recipeIngredient":["2 courgettes","200 g farine"],"recipeInstructions":[{"text":"Cuire 20 minutes."}]}</script>`;

test('extrait une recette Recipe JSON-LD avec attribution', () => { const raw = jsonLdBlocks(structured).flatMap(findRecipes)[0]; const recipe = normalizeRecipe(raw, { name: 'Source test' }, 'https://example.test/recette'); assert.equal(recipe.title, 'Tarte aux courgettes'); assert.equal(recipe.totalMinutes, 25); assert.equal(recipe.servings, 4); assert.match(recipe.attribution, /example\.test/); assert.equal(recipe.ingredients.length, 2); assert.ok(recipe.fingerprint); });

test('limite la collecte, met en cache et déduplique', async () => { let calls = 0; const fetchImpl = async url => { calls++; return { ok: true, text: async () => url.includes('search') ? '<a href="/recette/une">Une</a><a href="/recette/deux">Deux</a>' : structured }; }; const state = { providers: { demo: { name: 'Demo', enabled: true, searchUrl: 'https://demo.test/search?q={query}', hosts: ['demo.test'], minIntervalMs: 0, timeoutMs: 1000 } }, providerStatus: {}, recipeCache: {} }; const recipes = await new RecipeCollector({ fetchImpl }).search('courgette', state, 2); assert.equal(recipes.length, 1); assert.equal(Object.keys(state.recipeCache).length, 2); assert.equal(calls, 3); });

test('met une source en pause après trois échecs', async () => { let now = 1000; const state = { providers: { demo: { name: 'Demo', enabled: true, searchUrl: 'https://demo.test/search?q={query}', hosts: ['demo.test'], minIntervalMs: 0, timeoutMs: 10 } }, providerStatus: {}, recipeCache: {} }; const collector = new RecipeCollector({ fetchImpl: async () => { throw new Error('indisponible'); }, now: () => now }); await collector.search('a', state); await collector.search('b', state); await collector.search('c', state); assert.equal(state.providerStatus.demo.failures, 3); assert.ok(state.providerStatus.demo.disabledUntil > now); });

test('génère midi/soir et privilégie les restes quand Madame est seule', () => { const recipes = [{ id: 'summer', title: 'Salade été', season: 'Été', totalMinutes: 20, servings: 4, ingredients: [{ name: 'tomates', quantity: 4, unit: 'pièces' }] }, { id: 'winter', title: 'Potée', season: 'Hiver', totalMinutes: 90, servings: 4, ingredients: [{ name: 'chou', quantity: 1, unit: 'pièce' }] }]; const state = { recipes, shopping: [] }; const plan = generatePlan(state, { startDate: '2026-08-03', endDate: '2026-08-04', soloMadame: ['2026-08-04'] }); assert.equal(plan.meals.length, 4); assert.equal(plan.meals[0].servings, FAMILY_PORTIONS); assert.equal(plan.meals[2].servings, 1); assert.equal(plan.meals[2].fromLeftover, true); recalculatePlanShopping(state); assert.equal(state.shopping[0].quantity, 6); });
