const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { DEFAULT_PROVIDERS, RecipeCollector, fingerprint, canonical } = require('./lib/providers');
const { generatePlan, recalculatePlanShopping, scaledIngredients } = require('./lib/planner');
const { googleConfig, authorizationUrl, tokenRequest, fetchCalendars, fetchEvents, fetchZoneBHolidays, createOAuthState } = require('./lib/calendar');
const { familyCatalog } = require('./lib/family-catalog');
const { classifyRecipe } = require('./lib/recipe-classification');

const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const DATA_FILE = path.join(DATA_DIR, 'mealpilot.json');
const IMAGE_DIR = path.join(DATA_DIR, 'recipe-images');
const PUBLIC_DIR = path.join(__dirname, 'public');
const DAYS = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'];
const SEASONS = ['Printemps', 'Été', 'Automne', 'Hiver'];
const ALL_SEASONS = [...SEASONS];
const CATALOG_VERSION = 2;
const DEFAULT_WORK_SHIFT_TYPES = { morning: { label: 'Matin', start: '04:45', end: '12:45', meal: 'lunch', preference: 'transportable' }, 'return-morning': { label: 'R Matin', start: '04:45', end: '12:45', meal: 'lunch', preference: 'express' }, afternoon: { label: 'Après-midi', start: '12:45', end: '20:45', meal: 'dinner', preference: 'makeAhead' }, 'return-afternoon': { label: 'R Après-midi', start: '12:45', end: '20:45', meal: 'dinner', preference: 'express' }, night: { label: 'Nuit', start: '20:45', end: '04:45', meal: '', preference: 'normal' }, rest: { label: 'Repos', start: '', end: '', meal: '', preference: 'normal' }, leave: { label: 'Congés', start: '', end: '', meal: '', preference: 'normal' } };
const DEFAULT_FAMILY_SCHEDULE = { children: [{ id: 'child1', name: 'Enfant 1', portion: 0.6, presenceMode: 'always', calendarKeyword: '', canteenDays: [1, 2, 4, 5], centreDays: [] }, { id: 'child2', name: 'Enfant 2', portion: 0.4, presenceMode: 'always', calendarKeyword: '', canteenDays: [1, 2, 4, 5], centreDays: [] }, { id: 'child3', name: 'Noé', portion: 0.5, presenceMode: 'calendar', calendarKeyword: 'Noé', canteenDays: [], centreDays: [] }], exceptions: [], specialDays: [] };

const ingredient = (name, quantity = '', unit = '') => ({ name, quantity, unit });
const seasonalRecipeBase = () => [
  ['Risotto aux asperges', 'Printemps', 'Végétarien', 'Crémeux et lumineux, idéal au retour des beaux jours.', [ingredient('riz arborio', 300, 'g'), ingredient('asperges vertes', 500, 'g'), ingredient('bouillon de légumes', 1, 'L'), ingredient('parmesan', 80, 'g')], ['Préparer le bouillon et blanchir les asperges.', 'Nacrer le riz puis ajouter le bouillon progressivement.', 'Incorporer les asperges et le parmesan.']],
  ['Tarte petits pois et chèvre', 'Printemps', 'Végétarien', 'Une tarte familiale douce et fraîche.', [ingredient('pâte brisée', 1, 'pièce'), ingredient('petits pois', 300, 'g'), ingredient('fromage de chèvre', 150, 'g'), ingredient('œufs', 3, 'pièces')], ['Préchauffer le four à 190 °C.', 'Garnir la pâte avec les petits pois et le chèvre.', 'Verser les œufs battus et cuire 35 minutes.']],
  ['Ratatouille provençale', 'Été', 'Végétarien', 'Les légumes du soleil mijotés doucement.', [ingredient('courgettes', 2, 'pièces'), ingredient('aubergine', 1, 'pièce'), ingredient('poivrons', 2, 'pièces'), ingredient('tomates', 5, 'pièces')], ['Découper tous les légumes.', 'Faire revenir séparément les légumes.', 'Réunir, assaisonner et mijoter 30 minutes.']],
  ['Salade de poulet aux pêches', 'Été', 'Salade', 'Une assiette complète, fraîche et fruitée.', [ingredient('blancs de poulet', 4, 'pièces'), ingredient('pêches', 3, 'pièces'), ingredient('roquette', 150, 'g'), ingredient('amandes', 50, 'g')], ['Griller le poulet et les pêches.', 'Trancher le poulet.', 'Assembler avec la roquette et les amandes.']],
  ['Velouté de potimarron', 'Automne', 'Soupe', 'Réconfortant, simple et naturellement onctueux.', [ingredient('potimarron', 1, 'pièce'), ingredient('pommes de terre', 300, 'g'), ingredient('bouillon de légumes', 750, 'ml'), ingredient('crème', 10, 'cl')], ['Épépiner et couper le potimarron.', 'Cuire avec les pommes de terre dans le bouillon.', 'Mixer avec la crème et rectifier l’assaisonnement.']],
  ['Gratin de champignons', 'Automne', 'Végétarien', 'Un gratin généreux pour les soirées fraîches.', [ingredient('champignons', 600, 'g'), ingredient('pommes de terre', 800, 'g'), ingredient('crème', 25, 'cl'), ingredient('comté', 120, 'g')], ['Précuire les pommes de terre.', 'Poêler les champignons.', 'Monter le gratin et cuire 30 minutes à 190 °C.']],
  ['Bœuf-carottes', 'Hiver', 'Mijoté', 'Le grand classique familial qui se réchauffe très bien.', [ingredient('bœuf à braiser', 800, 'g'), ingredient('carottes', 1, 'kg'), ingredient('oignons', 2, 'pièces'), ingredient('bouillon de bœuf', 500, 'ml')], ['Faire dorer la viande.', 'Ajouter les légumes et le bouillon.', 'Couvrir et mijoter 2 heures à feu doux.']],
  ['Curry de pois chiches', 'Hiver', 'Végétarien', 'Épicé juste ce qu’il faut et prêt rapidement.', [ingredient('pois chiches', 500, 'g'), ingredient('lait de coco', 400, 'ml'), ingredient('tomates concassées', 400, 'g'), ingredient('riz', 300, 'g')], ['Faire revenir les épices.', 'Ajouter pois chiches, tomates et lait de coco.', 'Mijoter 20 minutes et servir avec le riz.']]
].map(([title, season, category, description, ingredients, preparation]) => ({ id: randomUUID(), title, season, category, description, ingredients, preparation, servings: 3, totalMinutes: /Mijoté/.test(category) ? 120 : /Salade/.test(category) ? 25 : 45, leftoverFriendly: !/Salade/.test(category), favorite: false, personal: false }));
const seasonalRecipes = () => familyCatalog();

const defaultState = () => ({ catalogVersion: CATALOG_VERSION, recipes: seasonalRecipes(), menu: Object.fromEntries(DAYS.map(day => [day, { lunch: null, dinner: null }])), plan: null, validatedPlan: null, leftovers: [], shopping: [], providers: structuredClone(DEFAULT_PROVIDERS), providerStatus: {}, recipeCache: {}, familySchedule: structuredClone(DEFAULT_FAMILY_SCHEDULE), workSchedule: { shiftTypes: structuredClone(DEFAULT_WORK_SHIFT_TYPES), entries: [] }, calendar: { connected: false, calendarId: 'primary', calendarName: 'Agenda principal', calendarIds: ['primary'], calendarNames: { primary: 'Agenda principal' }, events: [], schoolHolidays: [], lastSyncAt: null } });

function parseLegacyIngredient(value) {
  if (value && typeof value === 'object') return { name: String(value.name || '').trim(), quantity: value.quantity ?? '', unit: String(value.unit || '').trim() };
  const text = String(value || '').trim();
  const match = text.match(/^([\d.,½¼¾]+)\s*([a-zA-ZÀ-ÿ]+)?\s+(?:de |d')?(.*)$/);
  return match ? ingredient(match[3], match[1].replace(',', '.'), match[2] || '') : ingredient(text);
}

function migrateState(state) {
  if (state.catalogVersion !== CATALOG_VERSION) {
    state.recipes = seasonalRecipes(); state.catalogVersion = CATALOG_VERSION; state.deletedRecipeTitles = [];
    state.plan = null; state.validatedPlan = null; state.leftovers = [];
    state.menu = Object.fromEntries(DAYS.map(day => [day, { lunch: null, dinner: null }]));
    state.shopping = Array.isArray(state.shopping) ? state.shopping.filter(item => item.manual) : [];
  }
  state.recipes ||= [];
  state.deletedRecipeTitles ||= [];
  const knownSeasonalTitles = new Set(state.recipes.filter(recipe => recipe.personal === false).map(recipe => recipe.title));
  for (const recipe of seasonalRecipes()) if (!knownSeasonalTitles.has(recipe.title) && !state.deletedRecipeTitles.includes(recipe.title)) state.recipes.push(recipe);
  state.menu ||= Object.fromEntries(DAYS.map(day => [day, { lunch: null, dinner: null }]));
  state.shopping ||= [];
  state.plan ||= null; state.validatedPlan ||= null; state.leftovers ||= []; state.providers ||= {}; for (const [key, provider] of Object.entries(DEFAULT_PROVIDERS)) state.providers[key] = { ...structuredClone(provider), ...(state.providers[key] || {}) }; state.providerStatus ||= {}; state.recipeCache ||= {};
  state.calendar ||= {}; const legacyCalendarId = state.calendar.calendarId || 'primary'; const legacyCalendarName = state.calendar.calendarName || 'Agenda principal'; const calendarIds = Array.isArray(state.calendar.calendarIds) && state.calendar.calendarIds.length ? [...new Set(state.calendar.calendarIds.map(String))] : [legacyCalendarId]; const calendarNames = state.calendar.calendarNames && typeof state.calendar.calendarNames === 'object' ? state.calendar.calendarNames : { [legacyCalendarId]: legacyCalendarName }; Object.assign(state.calendar, { connected: Boolean(state.calendar.refreshToken), calendarId: calendarIds[0], calendarName: calendarIds.map(id => calendarNames[id] || id).join(', '), calendarIds, calendarNames, events: state.calendar.events || [], schoolHolidays: state.calendar.schoolHolidays || [], lastSyncAt: state.calendar.lastSyncAt || null });
  state.workSchedule ||= {}; state.workSchedule.shiftTypes = Object.fromEntries(Object.entries(DEFAULT_WORK_SHIFT_TYPES).map(([key, defaults]) => [key, { ...defaults, ...(state.workSchedule.shiftTypes?.[key] || {}) }])); state.workSchedule.entries = Array.isArray(state.workSchedule.entries) ? state.workSchedule.entries : [];
  Object.assign(state.workSchedule.shiftTypes.night, { meal: '', preference: 'normal' }); for (const entry of state.workSchedule.entries) if (entry.type === 'night' && entry.preference === 'workCanteen') entry.preference = 'auto';
  state.familySchedule ||= structuredClone(DEFAULT_FAMILY_SCHEDULE); state.familySchedule.children = DEFAULT_FAMILY_SCHEDULE.children.map((defaults,index)=>({ ...defaults, ...(state.familySchedule.children?.[index]||{}), id: defaults.id })); state.familySchedule.exceptions = Array.isArray(state.familySchedule.exceptions) ? state.familySchedule.exceptions : []; state.familySchedule.specialDays = Array.isArray(state.familySchedule.specialDays) ? state.familySchedule.specialDays : [];
  for (const day of DAYS) state.menu[day] ||= { lunch: null, dinner: null };
  for (const recipe of state.recipes) {
    recipe.ingredients = (recipe.ingredients || []).map(parseLegacyIngredient).filter(item => item.name);
    recipe.preparation = (recipe.preparation || []).map(String).filter(Boolean);
    recipe.personal ??= true;
    if (recipe.classificationVersion !== 4) {
      const classification = classifyRecipe(recipe);
      if (recipe.classificationVersion === 2) {
        recipe.category = classification.category;
        recipe.classificationVersion = classification.classificationVersion;
      } else Object.assign(recipe, classification);
    }
    recipe.season ||= 'Toute saison'; recipe.seasons = recipeSeasons(recipe); recipe.meals = recipeMeals(recipe); recipe.category ||= 'Autres plats'; recipe.favorite = Boolean(recipe.favorite); recipe.express ??= isExpressRecipe(recipe); recipe.transportable ??= /sandwich|wrap|salade|quiche|cake/i.test(`${recipe.title} ${recipe.category}`); recipe.leftoverFriendly ??= !/salade|tartare|soufflé|friture/i.test(`${recipe.title} ${recipe.category}`); recipe.makeAhead ??= recipe.leftoverFriendly;
  }
  if (state.plan?.meals) for (const meal of state.plan.meals) if (!state.recipes.some(recipe => recipe.id === meal.recipeId)) { meal.recipeId = null; meal.fromLeftover = false; }
  for (const item of state.shopping) { item.manual ??= true; item.name ||= item.label || ''; item.label ||= item.name; }
  return state;
}

function ensureState() { fs.mkdirSync(DATA_DIR, { recursive: true }); if (!fs.existsSync(DATA_FILE)) writeState(defaultState()); }
function readState() { ensureState(); const raw = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')); const before = JSON.stringify(raw); const state = migrateState(raw); if (JSON.stringify(state) !== before) writeState(state); return state; }
function writeState(state) { fs.mkdirSync(DATA_DIR, { recursive: true }); const temporary = `${DATA_FILE}.tmp`; fs.writeFileSync(temporary, JSON.stringify(state, null, 2)); fs.renameSync(temporary, DATA_FILE); }
function json(res, status, body) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(body === null ? '' : JSON.stringify(body)); }
function readBody(req) { return new Promise((resolve, reject) => { let data = ''; req.on('data', chunk => { data += chunk; if (data.length > 8_000_000) reject(new Error('Corps de requête trop volumineux')); }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(new Error('JSON invalide')); } }); req.on('error', reject); }); }
function cleanList(value) { return Array.isArray(value) ? value.map(item => String(item).trim()).filter(Boolean) : []; }
function deletedRecipeTitleSet(state) { return new Set((state.deletedRecipeTitles || []).map(canonical).filter(Boolean)); }
function cleanIngredients(value) { return Array.isArray(value) ? value.map(parseLegacyIngredient).filter(item => item.name) : []; }
function ingredientLabel(item) { return [item.quantity, item.unit, item.name].filter(value => value !== '' && value !== null && value !== undefined).join(' '); }
function publicState(state) { const copy = structuredClone(state); if (copy.calendar) { delete copy.calendar.accessToken; delete copy.calendar.refreshToken; delete copy.calendar.oauthState; delete copy.calendar.expiresAt; copy.calendar.configured = Boolean(googleConfig().clientId && googleConfig().redirectUri); } return copy; }

function recalculateShopping(state) {
  const manual = state.shopping.filter(item => item.manual);
  const checkedKeys = new Set(state.shopping.filter(item => item.checked && !item.manual).map(item => `${item.name}|${item.unit}`.toLocaleLowerCase('fr')));
  const totals = new Map();
  for (const recipeId of Object.values(state.menu).flatMap(day => [day.lunch, day.dinner]).filter(Boolean)) {
    const recipe = state.recipes.find(item => item.id === recipeId); if (!recipe) continue;
    for (const item of recipe.ingredients) {
      const key = `${item.name}|${item.unit}`.toLocaleLowerCase('fr'); const numeric = Number(String(item.quantity).replace(',', '.'));
      if (!totals.has(key)) totals.set(key, { name: item.name, unit: item.unit, quantity: Number.isFinite(numeric) ? 0 : item.quantity, count: 0 });
      const total = totals.get(key); if (Number.isFinite(numeric) && typeof total.quantity === 'number') total.quantity += numeric; else total.count += 1;
    }
  }
  state.shopping = [...manual, ...[...totals.entries()].map(([key, item]) => { const quantity = typeof item.quantity === 'number' ? item.quantity : item.quantity || (item.count > 1 ? item.count : ''); return { id: randomUUID(), name: item.name, quantity, unit: item.unit, label: ingredientLabel({ ...item, quantity }), checked: checkedKeys.has(key), manual: false }; })];
}

function recipePayload(body, existing = {}) {
  const seasons = Array.isArray(body.seasons) ? [...new Set(body.seasons.filter(season => SEASONS.includes(season)))] : SEASONS.includes(body.season) ? [body.season] : recipeSeasons(existing); const meals = Array.isArray(body.meals) ? [...new Set(body.meals.filter(meal => ['lunch', 'dinner'].includes(meal)))] : recipeMeals(existing); return { ...existing, title: String(body.title || '').trim(), description: String(body.description || '').trim(), image: Object.hasOwn(body, 'image') ? String(body.image || '') : existing.image || '', season: seasons.length === 4 ? 'Toute saison' : seasons[0] || 'Toute saison', seasons: seasons.length ? seasons : [...ALL_SEASONS], meals: meals.length ? meals : ['lunch', 'dinner'], category: String(body.category || 'Autre').trim(), servings: Math.max(1, Number(body.servings) || Number(existing.servings) || 3), prepMinutes: Math.max(0, Number(body.prepMinutes) || Number(existing.prepMinutes) || 0), totalMinutes: Math.max(0, Number(body.totalMinutes) || Number(existing.totalMinutes) || 0), express: Object.hasOwn(body, 'express') ? Boolean(body.express) : existing.express ?? false, transportable: Object.hasOwn(body, 'transportable') ? Boolean(body.transportable) : existing.transportable ?? false, makeAhead: Object.hasOwn(body, 'makeAhead') ? Boolean(body.makeAhead) : existing.makeAhead ?? false, leftoverFriendly: Object.hasOwn(body, 'leftoverFriendly') ? Boolean(body.leftoverFriendly) : existing.leftoverFriendly ?? true, ingredients: cleanIngredients(body.ingredients), preparation: cleanList(body.preparation), personal: existing.personal ?? true, favorite: existing.favorite ?? false };
}

function saveRecipeImage(value) { const match = String(value || '').match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/); if (!match) throw new Error('Image invalide. Utilisez JPG, PNG ou WebP.'); const bytes = Buffer.from(match[2], 'base64'); if (!bytes.length || bytes.length > 5_000_000) throw new Error('La photo doit faire moins de 5 Mo.'); fs.mkdirSync(IMAGE_DIR, { recursive: true }); const extension = match[1] === 'jpeg' ? 'jpg' : match[1]; const filename = `${randomUUID()}.${extension}`; fs.writeFileSync(path.join(IMAGE_DIR, filename), bytes); return `/uploads/${filename}`; }
function prepareRecipeImage(body, existing = {}) { if (body.removeImage) body.image = ''; else if (body.imageData) body.image = saveRecipeImage(body.imageData); else if (!Object.hasOwn(body, 'image')) body.image = existing.image || ''; delete body.imageData; delete body.removeImage; return body; }

function recipeSeasons(recipe) {
  if (Array.isArray(recipe.seasons) && recipe.seasons.length) return [...new Set(recipe.seasons.filter(season => SEASONS.includes(season)))];
  if (recipe.season === 'Toute saison') return [...ALL_SEASONS];
  const value = `${recipe.title || ''} ${recipe.category || ''}`.toLocaleLowerCase('fr');
  if (recipe.season === 'Hiver' && /carbonade|mijot|potée|bœuf|boeuf|gratin|soupe|velouté|curry/.test(value)) return ['Automne', 'Hiver'];
  if (recipe.season === 'Été' && /salade|grill|brochette|fraîche|fraiche/.test(value)) return ['Printemps', 'Été'];
  return SEASONS.includes(recipe.season) ? [recipe.season] : [...ALL_SEASONS];
}

function isExpressRecipe(recipe) {
  const duration = Number(recipe.totalMinutes || recipe.prepMinutes || 0);
  return (duration > 0 && duration <= 30) || /express|rapide|omelette|croque|salade|sandwich|wrap/i.test(`${recipe.title || ''} ${recipe.category || ''}`);
}

function recipeMeals(recipe) {
  return Array.isArray(recipe.meals) && recipe.meals.length ? [...new Set(recipe.meals.filter(meal => ['lunch', 'dinner'].includes(meal)))] : ['lunch', 'dinner'];
}

async function api(req, res, pathname, url) {
  if (pathname === '/api/health' && req.method === 'GET') return json(res, 200, { status: 'ok' });
  if (pathname === '/api/state' && req.method === 'GET') return json(res, 200, publicState(readState()));
  const state = readState();
  if (pathname === '/api/work-schedule-v2' && req.method === 'PUT') { const body=await readBody(req),preferences=new Set(['auto','normal','express','transportable','makeAhead','workCanteen']),shiftTypes={}; for(const [key,defaults] of Object.entries(DEFAULT_WORK_SHIFT_TYPES)){const input=body.shiftTypes?.[key]||{}; shiftTypes[key]={...defaults,start:/^\d{2}:\d{2}$/.test(input.start)?input.start:defaults.start,end:/^\d{2}:\d{2}$/.test(input.end)?input.end:defaults.end,preference:preferences.has(input.preference)&&input.preference!=='auto'?input.preference:defaults.preference};} const entries=Array.isArray(body.entries)?body.entries.filter(entry=>/^\d{4}-\d{2}-\d{2}$/.test(entry.date)&&shiftTypes[entry.type]).map(entry=>({date:entry.date,type:entry.type,preference:preferences.has(entry.preference)?entry.preference:'auto'})).slice(-366):state.workSchedule.entries; state.workSchedule={shiftTypes,entries:[...new Map(entries.map(entry=>[entry.date,entry])).values()].sort((a,b)=>a.date.localeCompare(b.date))}; writeState(state); return json(res,200,state.workSchedule); }
  if (pathname === '/api/family-schedule-v2' && req.method === 'PUT') { const body=await readBody(req),statuses=new Set(['home','canteen','centre','outside','absent']),specialTypes=new Set(['canteenClosed','bridge']),today=new Date().toISOString().slice(0,10); const children=DEFAULT_FAMILY_SCHEDULE.children.map((defaults,index)=>{const existing=state.familySchedule.children?.[index]||defaults,input=body.children?.[index]||{},days=value=>Array.isArray(value)?[...new Set(value.map(Number).filter(day=>day>=1&&day<=5))]:[]; const birthDate=/^\d{4}-\d{2}-\d{2}$/.test(input.birthDate||'')&&input.birthDate<=today?input.birthDate:''; return {...defaults,name:String(input.name||defaults.name).trim().slice(0,40),birthDate,portion:Math.max(0,Math.min(2,Number(existing.portion)||defaults.portion)),canteenDays:days(input.canteenDays),centreDays:days(input.centreDays)};}); const childIds=new Set(children.map(child=>child.id)),exceptions=Array.isArray(body.exceptions)?body.exceptions.filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&childIds.has(item.memberId)).map(item=>({date:item.date,memberId:item.memberId,lunch:statuses.has(item.lunch)?item.lunch:'home',dinner:statuses.has(item.dinner)?item.dinner:'home'})).slice(-732):[],specialDays=Array.isArray(body.specialDays)?body.specialDays.filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&specialTypes.has(item.type)).map(item=>({date:item.date,type:item.type,label:String(item.label||'').trim().slice(0,80)})).slice(-366):[]; state.familySchedule={children,exceptions:[...new Map(exceptions.map(item=>[`${item.date}|${item.memberId}`,item])).values()].sort((a,b)=>a.date.localeCompare(b.date)),specialDays:[...new Map(specialDays.map(item=>[item.date,item])).values()].sort((a,b)=>a.date.localeCompare(b.date))}; writeState(state); return json(res,200,state.familySchedule); }
  if (pathname === '/api/calendar/auth' && req.method === 'GET') { state.calendar.oauthState = createOAuthState(); writeState(state); return json(res, 200, { url: authorizationUrl(state.calendar.oauthState) }); }
  if (pathname === '/api/calendar/callback' && req.method === 'GET') { if (!url.searchParams.get('code') || url.searchParams.get('state') !== state.calendar.oauthState) return json(res, 400, { error: 'Retour OAuth invalide.' }); const token = await tokenRequest({ code: url.searchParams.get('code'), redirect_uri: googleConfig().redirectUri, grant_type: 'authorization_code' }); state.calendar.accessToken = token.access_token; state.calendar.refreshToken = token.refresh_token || state.calendar.refreshToken; state.calendar.expiresAt = Date.now() + Number(token.expires_in || 3600) * 1000; state.calendar.connected = true; delete state.calendar.oauthState; writeState(state); res.writeHead(302, { Location: '/#calendar' }); return res.end(); }
  if (pathname === '/api/calendar/calendars' && req.method === 'GET') return json(res, 200, await fetchCalendars(state.calendar));
  if (pathname === '/api/calendar' && req.method === 'PATCH') { const body = await readBody(req); const ids = Array.isArray(body.calendarIds) ? [...new Set(body.calendarIds.map(String).filter(Boolean))] : [String(body.calendarId || 'primary')]; if (!ids.length) return json(res, 400, { error: 'Choisissez au moins un agenda.' }); const names = body.calendarNames && typeof body.calendarNames === 'object' ? Object.fromEntries(ids.map(id => [id, String(body.calendarNames[id] || id)])) : Object.fromEntries(ids.map(id => [id, id === body.calendarId ? String(body.calendarName || id) : id])); state.calendar.calendarIds = ids; state.calendar.calendarNames = names; state.calendar.calendarId = ids[0]; state.calendar.calendarName = ids.map(id => names[id]).join(', '); writeState(state); return json(res, 200, publicState(state).calendar); }
  if (pathname === '/api/calendar/sync' && req.method === 'POST') { const body = await readBody(req); const startDate = /^\d{4}-\d{2}-\d{2}$/.test(body.startDate) ? body.startDate : new Date().toISOString().slice(0, 10); const defaultEnd = new Date(`${startDate}T12:00:00`); defaultEnd.setDate(defaultEnd.getDate() + 61); const requestedEnd = /^\d{4}-\d{2}-\d{2}$/.test(body.endDate) ? body.endDate : null; const endDate = !requestedEnd || requestedEnd === startDate ? defaultEnd.toISOString().slice(0, 10) : requestedEnd; const [events, schoolHolidays] = await Promise.all([fetchEvents(state.calendar, startDate, endDate), fetchZoneBHolidays(startDate, endDate)]); state.calendar.events = events; state.calendar.schoolHolidays = schoolHolidays; state.calendar.lastSyncAt = new Date().toISOString(); writeState(state); return json(res, 200, publicState(state).calendar); }
  if (pathname === '/api/calendar/disconnect' && req.method === 'DELETE') { state.calendar = { connected: false, calendarId: 'primary', calendarName: 'Agenda principal', calendarIds: ['primary'], calendarNames: { primary: 'Agenda principal' }, events: [], schoolHolidays: state.calendar.schoolHolidays || [], lastSyncAt: null }; writeState(state); return json(res, 204, null); }
  if (pathname === '/api/work-schedule' && req.method === 'PUT') { const body = await readBody(req); const preferences = new Set(['auto', 'normal', 'express', 'transportable', 'makeAhead']); const shiftTypes = {}; for (const [key, defaults] of Object.entries(DEFAULT_WORK_SHIFT_TYPES)) { const input = body.shiftTypes?.[key] || {}; shiftTypes[key] = { ...defaults, start: /^\d{2}:\d{2}$/.test(input.start) ? input.start : defaults.start, end: /^\d{2}:\d{2}$/.test(input.end) ? input.end : defaults.end, preference: preferences.has(input.preference) && input.preference !== 'auto' ? input.preference : defaults.preference }; } const entries = Array.isArray(body.entries) ? body.entries.filter(entry => /^\d{4}-\d{2}-\d{2}$/.test(entry.date) && shiftTypes[entry.type]).map(entry => ({ date: entry.date, type: entry.type, preference: preferences.has(entry.preference) ? entry.preference : 'auto' })).slice(-366) : state.workSchedule.entries; state.workSchedule = { shiftTypes, entries: [...new Map(entries.map(entry => [entry.date, entry])).values()].sort((a, b) => a.date.localeCompare(b.date)) }; writeState(state); return json(res, 200, state.workSchedule); }
  if (pathname === '/api/family-schedule' && req.method === 'PUT') { const body=await readBody(req); const statuses=new Set(['home','canteen','centre','outside','absent']); const specialTypes=new Set(['canteenClosed','bridge']); const children=DEFAULT_FAMILY_SCHEDULE.children.map((defaults,index)=>{const input=body.children?.[index]||{}; const days=value=>Array.isArray(value)?[...new Set(value.map(Number).filter(day=>day>=1&&day<=5))]:[]; return {...defaults,name:String(input.name||defaults.name).trim().slice(0,40),portion:Math.max(0,Math.min(2,Number(input.portion)||defaults.portion)),canteenDays:days(input.canteenDays),centreDays:days(input.centreDays)};}); const childIds=new Set(children.map(child=>child.id)); const exceptions=Array.isArray(body.exceptions)?body.exceptions.filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&childIds.has(item.memberId)).map(item=>({date:item.date,memberId:item.memberId,lunch:statuses.has(item.lunch)?item.lunch:'home',dinner:statuses.has(item.dinner)?item.dinner:'home'})).slice(-732):[]; const specialDays=Array.isArray(body.specialDays)?body.specialDays.filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&specialTypes.has(item.type)).map(item=>({date:item.date,type:item.type,label:String(item.label||'').trim().slice(0,80)})).slice(-366):[]; state.familySchedule={children,exceptions:[...new Map(exceptions.map(item=>[`${item.date}|${item.memberId}`,item])).values()].sort((a,b)=>a.date.localeCompare(b.date)),specialDays:[...new Map(specialDays.map(item=>[item.date,item])).values()].sort((a,b)=>a.date.localeCompare(b.date))}; writeState(state); return json(res,200,state.familySchedule); }
  if (pathname === '/api/providers' && req.method === 'GET') return json(res, 200, { providers: state.providers, status: state.providerStatus });
  const providerMatch = pathname.match(/^\/api\/providers\/([^/]+)$/);
  if (providerMatch && req.method === 'PATCH') { const key = decodeURIComponent(providerMatch[1]); if (!state.providers[key]) return json(res, 404, { error: 'Fournisseur introuvable.' }); const body = await readBody(req); if (Object.hasOwn(body, 'enabled')) { state.providers[key].enabled = Boolean(body.enabled); if (body.enabled && state.providerStatus[key]) { state.providerStatus[key].failures = 0; state.providerStatus[key].autoDisabled = false; delete state.providerStatus[key].disabledReason; } } for (const setting of ['timeoutMs', 'minIntervalMs']) if (Number.isFinite(Number(body[setting]))) state.providers[key][setting] = Math.max(250, Number(body[setting])); writeState(state); return json(res, 200, state.providers[key]); }
  if (pathname === '/api/recipes/collect' && req.method === 'POST') { const body = await readBody(req); const query = String(body.query || '').trim(); if (!query) return json(res, 400, { error: 'Recherche requise.' }); const collector = new RecipeCollector(); const found = await collector.search(query, state, Math.min(12, Math.max(1, Number(body.limit) || 8))); const known = new Set(state.recipes.map(recipe => recipe.fingerprint || fingerprint(recipe))); const deletedTitles = deletedRecipeTitleSet(state); const candidates = found.filter(recipe => !known.has(recipe.fingerprint) && !deletedTitles.has(canonical(recipe.title))); writeState(state); return json(res, 200, { found: found.length, candidates, providerStatus: state.providerStatus }); }
  if (pathname === '/api/recipes/import-url' && req.method === 'POST') { const body = await readBody(req); const collector = new RecipeCollector(); const candidate = await collector.importUrl(body.url, state); const known = new Set(state.recipes.map(recipe => recipe.fingerprint || fingerprint(recipe))); if (known.has(candidate.fingerprint)) return json(res, 409, { error: 'Cette recette existe déjà dans MealPilot.' }); if (deletedRecipeTitleSet(state).has(canonical(candidate.title))) return json(res, 409, { error: 'Cette recette a déjà été supprimée et ne sera pas réimportée.' }); writeState(state); return json(res, 200, { candidate }); }
  if (pathname === '/api/recipes/import' && req.method === 'POST') { const body = await readBody(req); const candidates = Array.isArray(body.recipes) ? body.recipes.slice(0, 12) : []; const known = new Set(state.recipes.map(recipe => recipe.fingerprint || fingerprint(recipe))); const deletedTitles = deletedRecipeTitleSet(state); const added = []; for (const candidate of candidates) { const recipe = { ...candidate, id: randomUUID(), title: String(candidate.title || '').trim(), ingredients: cleanIngredients(candidate.ingredients), preparation: cleanList(candidate.preparation), personal: false, favorite: false }; Object.assign(recipe, classifyRecipe(recipe)); recipe.express ??= isExpressRecipe(recipe); recipe.fingerprint = fingerprint(recipe); if (recipe.title && recipe.ingredients.length && !known.has(recipe.fingerprint) && !deletedTitles.has(canonical(recipe.title))) { known.add(recipe.fingerprint); state.recipes.push(recipe); added.push(recipe); } } writeState(state); return json(res, 201, { added: added.length, recipes: added }); }
  if (pathname === '/api/plan/generate' && req.method === 'POST') { const body = await readBody(req); if (!/^\d{4}-\d{2}-\d{2}$/.test(body.startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(body.endDate)) return json(res, 400, { error: 'Période invalide.' }); try { const tasks = [fetchZoneBHolidays(body.startDate, body.endDate)]; if (state.calendar.refreshToken) tasks.push(fetchEvents(state.calendar, body.startDate, body.endDate)); const [holidays, events] = await Promise.all(tasks); state.calendar.schoolHolidays = holidays; if (events) state.calendar.events = events; state.calendar.lastSyncAt = new Date().toISOString(); delete state.calendar.syncError; } catch (error) { state.calendar.syncError = error.message; } const plan = generatePlan(state, body); recalculatePlanShopping(state); writeState(state); return json(res, 200, { plan, shopping: state.shopping, calendarWarning: state.calendar.syncError || null }); }
  if (pathname === '/api/plan/validate' && req.method === 'POST') { if (!state.plan?.meals?.length) return json(res, 400, { error: 'Générez un menu avant de le valider.' }); const meals = state.plan.meals.map(meal => { const recipe = state.recipes.find(item => item.id === meal.recipeId); if (!recipe) return null; const exactServings = meal.fromLeftover ? meal.servings : meal.cookedServings || meal.servings; return { ...structuredClone(meal), exactServings, scaledIngredients: scaledIngredients(recipe, exactServings), recipe: structuredClone(recipe) }; }); if (meals.some(meal => !meal)) return json(res, 400, { error: 'Une recette du menu est introuvable.' }); state.validatedPlan = { startDate: state.plan.startDate, endDate: state.plan.endDate, generatedAt: state.plan.generatedAt, validatedAt: new Date().toISOString(), meals }; writeState(state); return json(res, 200, state.validatedPlan); }
  const planMealMatch = pathname.match(/^\/api\/plan\/meals\/([^/]+)$/);
  if (planMealMatch && req.method === 'PATCH') { const meal = state.plan?.meals.find(item => item.id === decodeURIComponent(planMealMatch[1])); if (!meal) return json(res, 404, { error: 'Repas introuvable.' }); const body = await readBody(req); if (!state.recipes.some(item => item.id === body.recipeId)) return json(res, 400, { error: 'Recette invalide.' }); meal.recipeId = body.recipeId; meal.fromLeftover = false; recalculatePlanShopping(state); writeState(state); return json(res, 200, { meal, shopping: state.shopping }); }
  if (pathname === '/api/recipes' && req.method === 'POST') {
    const recipe = recipePayload(prepareRecipeImage(await readBody(req)));
    if (!recipe.title || !recipe.ingredients.length || !recipe.preparation.length) return json(res, 400, { error: 'Titre, ingrédients et préparation sont requis.' });
    recipe.id = randomUUID(); state.recipes.push(recipe); writeState(state); return json(res, 201, recipe);
  }
  const favoriteMatch = pathname.match(/^\/api\/recipes\/([^/]+)\/favorite$/);
  if (favoriteMatch && req.method === 'PATCH') { const recipe = state.recipes.find(item => item.id === decodeURIComponent(favoriteMatch[1])); if (!recipe) return json(res, 404, { error: 'Recette introuvable.' }); recipe.favorite = !recipe.favorite; writeState(state); return json(res, 200, recipe); }
  const recipeMatch = pathname.match(/^\/api\/recipes\/([^/]+)$/);
  if (recipeMatch && req.method === 'PUT') { const index = state.recipes.findIndex(item => item.id === decodeURIComponent(recipeMatch[1])); if (index < 0) return json(res, 404, { error: 'Recette introuvable.' }); const recipe = recipePayload(prepareRecipeImage(await readBody(req), state.recipes[index]), state.recipes[index]); if (!recipe.title || !recipe.ingredients.length || !recipe.preparation.length) return json(res, 400, { error: 'Titre, ingrédients et préparation sont requis.' }); recipe.fingerprint = fingerprint(recipe); state.recipes[index] = recipe; if (state.plan?.meals) recalculatePlanShopping(state); else recalculateShopping(state); writeState(state); return json(res, 200, recipe); }
  if (recipeMatch && req.method === 'DELETE') { const index = state.recipes.findIndex(item => item.id === decodeURIComponent(recipeMatch[1])); if (index < 0) return json(res, 404, { error: 'Recette introuvable.' }); const removed = state.recipes[index]; const id = removed.id; state.deletedRecipeTitles ||= []; if (!state.deletedRecipeTitles.includes(removed.title)) state.deletedRecipeTitles.push(removed.title); state.recipes.splice(index, 1); for (const meals of Object.values(state.menu)) { if (meals.lunch === id) meals.lunch = null; if (meals.dinner === id) meals.dinner = null; } if (state.plan?.meals) { for (const meal of state.plan.meals) if (meal.recipeId === id) { meal.recipeId = null; meal.fromLeftover = false; } recalculatePlanShopping(state); } else recalculateShopping(state); writeState(state); return json(res, 204, null); }
  if (pathname === '/api/menu' && req.method === 'PUT') { const body = await readBody(req); if (!DAYS.includes(body.day) || !['lunch', 'dinner'].includes(body.meal)) return json(res, 400, { error: 'Créneau invalide.' }); if (body.recipeId !== null && !state.recipes.some(item => item.id === body.recipeId)) return json(res, 400, { error: 'Recette invalide.' }); state.menu[body.day][body.meal] = body.recipeId; recalculateShopping(state); writeState(state); return json(res, 200, { menu: state.menu, shopping: state.shopping }); }
  if (pathname === '/api/shopping/from-menu' && req.method === 'POST') { recalculateShopping(state); writeState(state); return json(res, 200, state.shopping); }
  if (pathname === '/api/shopping' && req.method === 'DELETE') { state.shopping = []; writeState(state); return json(res, 204, null); }
  if (pathname === '/api/shopping' && req.method === 'POST') { const body = await readBody(req); const label = String(body.label || '').trim(); if (!label) return json(res, 400, { error: 'Article requis.' }); const item = { id: randomUUID(), name: label, label, quantity: '', unit: '', checked: false, manual: true }; state.shopping.push(item); writeState(state); return json(res, 201, item); }
  const shoppingMatch = pathname.match(/^\/api\/shopping\/([^/]+)$/);
  if (shoppingMatch && req.method === 'PATCH') { const item = state.shopping.find(entry => entry.id === decodeURIComponent(shoppingMatch[1])); if (!item) return json(res, 404, { error: 'Article introuvable.' }); const body = await readBody(req); if (Object.hasOwn(body, 'label')) { const label = String(body.label || '').trim(); if (!label) return json(res, 400, { error: 'Article requis.' }); item.label = label; item.name = label; item.manual = true; } else item.checked = !item.checked; writeState(state); return json(res, 200, item); }
  if (shoppingMatch && req.method === 'DELETE') { const index = state.shopping.findIndex(entry => entry.id === decodeURIComponent(shoppingMatch[1])); if (index < 0) return json(res, 404, { error: 'Article introuvable.' }); state.shopping.splice(index, 1); writeState(state); return json(res, 204, null); }
  return json(res, 404, { error: 'Route introuvable.' });
}

function staticFile(res, pathname) { const upload = pathname.match(/^\/uploads\/([a-z0-9-]+\.(?:jpg|png|webp))$/i); const base = upload ? IMAGE_DIR : PUBLIC_DIR; const requested = upload ? upload[1] : pathname === '/' ? 'index.html' : pathname.slice(1); const file = path.resolve(base, requested); if (!file.startsWith(`${path.resolve(base)}${path.sep}`) && file !== path.join(PUBLIC_DIR, 'index.html')) return json(res, 403, { error: 'Accès refusé.' }); if (!fs.existsSync(file) || !fs.statSync(file).isFile()) return json(res, 404, { error: 'Fichier introuvable.' }); const types = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.svg': 'image/svg+xml', '.jpg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp' }; res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream', 'Cache-Control': upload ? 'public, max-age=31536000, immutable' : 'no-cache' }); fs.createReadStream(file).pipe(res); }
const server = http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const pathname = url.pathname; try { if (pathname.startsWith('/api/')) await api(req, res, pathname, url); else staticFile(res, pathname); } catch (error) { console.error(error); json(res, 500, { error: error.message || 'Erreur interne.' }); } });
if (require.main === module) server.listen(PORT, '0.0.0.0', () => console.log(`MealPilot disponible sur le port ${PORT}`));
module.exports = { server, defaultState, DAYS, recalculateShopping };
