const SPRITE = '/assets/french-classics.png';
const ingredient = (name, quantity = '', unit = '') => ({ name, quantity, unit });
const positions = Array.from({ length: 20 }, (_, index) => `${(index % 5) * 25}% ${Math.floor(index / 5) * 33.333}%`);

const definitions = [
  ['blanquette-veau', 'Blanquette de veau', 'Mijoté', 25, 95, 'Un plat doux et familial, avec une sauce crémeuse et des légumes.', [ingredient('veau à mijoter', 800, 'g'), ingredient('carottes', 4, 'pièces'), ingredient('champignons de Paris', 250, 'g'), ingredient('oignon', 1, 'pièce'), ingredient('crème fraîche', 20, 'cl'), ingredient('farine', 30, 'g'), ingredient('bouillon', 750, 'ml')], ['Faire revenir doucement le veau sans le colorer.', 'Ajouter carottes, oignon et bouillon puis mijoter 1 heure.', 'Ajouter les champignons.', 'Lier la sauce avec la farine et la crème puis cuire encore 10 minutes.']],
  ['hachis-parmentier', 'Hachis parmentier', 'Gratin', 25, 55, 'Le classique pratique à préparer à l’avance et à réchauffer.', [ingredient('bœuf haché', 500, 'g'), ingredient('pommes de terre', 1, 'kg'), ingredient('oignon', 1, 'pièce'), ingredient('lait', 20, 'cl'), ingredient('beurre', 40, 'g'), ingredient('fromage râpé', 80, 'g')], ['Cuire les pommes de terre puis les écraser avec le lait et le beurre.', 'Faire revenir l’oignon et le bœuf.', 'Déposer la viande dans un plat, couvrir de purée et de fromage.', 'Gratiner 20 minutes à 200 °C.']],
  ['quiche-lorraine', 'Quiche lorraine', 'Tarte', 15, 45, 'Une quiche simple pour le soir, délicieuse avec une salade.', [ingredient('pâte brisée', 1, 'pièce'), ingredient('lardons', 200, 'g'), ingredient('œufs', 3, 'pièces'), ingredient('crème fraîche', 25, 'cl'), ingredient('lait', 10, 'cl'), ingredient('muscade', 1, 'pincée')], ['Préchauffer le four à 190 °C.', 'Faire revenir les lardons puis les répartir sur la pâte.', 'Mélanger œufs, crème, lait et muscade.', 'Verser et cuire environ 30 minutes.']],
  ['boeuf-bourguignon', 'Bœuf bourguignon', 'Mijoté', 25, 150, 'Un mijoté généreux qui est encore meilleur réchauffé.', [ingredient('bœuf à braiser', 900, 'g'), ingredient('carottes', 4, 'pièces'), ingredient('champignons', 250, 'g'), ingredient('oignons', 2, 'pièces'), ingredient('vin rouge', 50, 'cl'), ingredient('bouillon de bœuf', 30, 'cl')], ['Faire dorer la viande et les oignons.', 'Ajouter carottes, vin et bouillon.', 'Couvrir et mijoter 2 heures.', 'Ajouter les champignons 20 minutes avant la fin.']],
  ['gratin-dauphinois', 'Gratin dauphinois', 'Gratin', 20, 75, 'Pommes de terre fondantes à la crème, parfaites avec une salade ou une viande.', [ingredient('pommes de terre', 1.2, 'kg'), ingredient('crème liquide', 40, 'cl'), ingredient('lait', 30, 'cl'), ingredient('ail', 1, 'gousse'), ingredient('muscade', 1, 'pincée')], ['Éplucher et trancher finement les pommes de terre.', 'Frotter le plat avec l’ail.', 'Alterner pommes de terre, assaisonnement, lait et crème.', 'Cuire 1 heure à 180 °C.']],
  ['poulet-basquaise', 'Poulet basquaise', 'Mijoté', 20, 60, 'Poulet, tomates et poivrons dans une sauce colorée.', [ingredient('cuisses de poulet', 4, 'pièces'), ingredient('poivrons', 3, 'pièces'), ingredient('tomates concassées', 500, 'g'), ingredient('oignon', 1, 'pièce'), ingredient('ail', 2, 'gousses')], ['Faire dorer le poulet puis le réserver.', 'Faire fondre oignon, ail et poivrons.', 'Ajouter les tomates et remettre le poulet.', 'Couvrir et mijoter 35 minutes.']],
  ['croque-monsieur', 'Croque-monsieur et salade', 'Rapide', 10, 20, 'Un dîner express et croustillant apprécié de toute la famille.', [ingredient('pain de mie', 8, 'tranches'), ingredient('jambon blanc', 4, 'tranches'), ingredient('emmental', 160, 'g'), ingredient('crème fraîche', 4, 'c. à soupe'), ingredient('salade verte', 1, 'pièce')], ['Tartiner légèrement le pain de crème.', 'Garnir de jambon et d’emmental puis refermer.', 'Cuire 8 à 10 minutes au four ou à la poêle.', 'Servir avec la salade assaisonnée.']],
  ['lentilles-saucisses', 'Lentilles saucisses', 'Mijoté', 15, 55, 'Un plat complet, économique et facile à réchauffer.', [ingredient('lentilles vertes', 350, 'g'), ingredient('saucisses fumées', 4, 'pièces'), ingredient('carottes', 2, 'pièces'), ingredient('oignon', 1, 'pièce'), ingredient('bouillon', 1, 'L')], ['Rincer les lentilles.', 'Faire revenir oignon et carottes.', 'Ajouter lentilles, bouillon et saucisses.', 'Mijoter 35 à 40 minutes.']],
  ['endives-jambon', 'Endives au jambon', 'Gratin', 20, 55, 'Des endives fondantes roulées dans le jambon et gratinées.', [ingredient('endives', 4, 'pièces'), ingredient('jambon blanc', 4, 'tranches'), ingredient('lait', 50, 'cl'), ingredient('farine', 40, 'g'), ingredient('beurre', 40, 'g'), ingredient('fromage râpé', 100, 'g')], ['Cuire les endives à la vapeur puis bien les égoutter.', 'Préparer une béchamel avec beurre, farine et lait.', 'Rouler chaque endive dans une tranche de jambon.', 'Napper, parsemer de fromage et gratiner 20 minutes.']],
  ['tomates-farcies', 'Tomates farcies et riz', 'Four', 20, 55, 'Un plat familial complet qui se prépare facilement.', [ingredient('grosses tomates', 6, 'pièces'), ingredient('chair à saucisse', 500, 'g'), ingredient('riz', 250, 'g'), ingredient('oignon', 1, 'pièce'), ingredient('persil', 2, 'c. à soupe')], ['Évider les tomates et conserver la chair.', 'Mélanger la viande avec oignon, persil et chair de tomate.', 'Farcir les tomates et les placer sur le riz avec un peu d’eau.', 'Cuire 40 minutes à 190 °C.']],
  ['steak-puree', 'Steak haché purée', 'Rapide', 15, 30, 'Le repas familial simple et efficace par excellence.', [ingredient('steaks hachés', 4, 'pièces'), ingredient('pommes de terre', 1, 'kg'), ingredient('lait', 20, 'cl'), ingredient('beurre', 40, 'g')], ['Cuire les pommes de terre à l’eau salée.', 'Les écraser avec le lait chaud et le beurre.', 'Cuire les steaks à la poêle selon la cuisson souhaitée.', 'Servir immédiatement avec la purée.']],
  ['cordon-bleu-haricots', 'Cordon bleu et haricots verts', 'Rapide', 10, 25, 'Un repas rapide accompagné de légumes verts.', [ingredient('cordons bleus', 4, 'pièces'), ingredient('haricots verts', 600, 'g'), ingredient('beurre', 20, 'g'), ingredient('ail', 1, 'gousse')], ['Cuire les cordons bleus au four ou à la poêle.', 'Cuire les haricots verts.', 'Les faire revenir rapidement avec beurre et ail.', 'Servir bien chaud.']],
  ['omelette-pommes-terre', 'Omelette aux pommes de terre', 'Rapide', 15, 30, 'Une omelette consistante idéale pour un déjeuner pressé.', [ingredient('œufs', 8, 'pièces'), ingredient('pommes de terre', 600, 'g'), ingredient('oignon', 1, 'pièce'), ingredient('huile', 2, 'c. à soupe')], ['Couper les pommes de terre en petits dés.', 'Les cuire à la poêle avec l’oignon.', 'Verser les œufs battus et assaisonnés.', 'Cuire à feu doux jusqu’à la consistance souhaitée.']],
  ['poisson-citron', 'Poisson blanc sauce citron et riz', 'Rapide', 15, 30, 'Un poisson doux avec une sauce citronnée très simple.', [ingredient('filets de poisson blanc', 4, 'pièces'), ingredient('riz', 300, 'g'), ingredient('crème liquide', 20, 'cl'), ingredient('citron', 1, 'pièce'), ingredient('persil', 1, 'c. à soupe')], ['Cuire le riz.', 'Poêler doucement les filets de poisson.', 'Ajouter crème, jus de citron et persil.', 'Laisser épaissir 3 minutes et servir avec le riz.']],
  ['coquillettes-jambon', 'Coquillettes jambon fromage', 'Rapide', 10, 20, 'Le classique réconfortant prêt en vingt minutes.', [ingredient('coquillettes', 400, 'g'), ingredient('jambon blanc', 4, 'tranches'), ingredient('crème fraîche', 15, 'cl'), ingredient('emmental râpé', 120, 'g')], ['Cuire les coquillettes.', 'Découper le jambon.', 'Mélanger les pâtes chaudes avec jambon, crème et fromage.', 'Poivrer et servir aussitôt.']],
  ['pot-au-feu', 'Pot-au-feu', 'Mijoté', 25, 180, 'Viande et légumes longuement mijotés dans un bouillon parfumé.', [ingredient('bœuf à pot-au-feu', 1.2, 'kg'), ingredient('carottes', 5, 'pièces'), ingredient('poireaux', 3, 'pièces'), ingredient('navets', 3, 'pièces'), ingredient('pommes de terre', 600, 'g'), ingredient('bouquet garni', 1, 'pièce')], ['Couvrir la viande d’eau froide et porter à frémissement.', 'Écumer puis ajouter le bouquet garni.', 'Ajouter les légumes sauf les pommes de terre et mijoter 2 heures.', 'Ajouter les pommes de terre pour les 30 dernières minutes.']],
  ['navarin-agneau', 'Navarin d’agneau', 'Mijoté', 25, 100, 'Un ragoût d’agneau tendre aux légumes.', [ingredient('épaule d’agneau', 800, 'g'), ingredient('pommes de terre', 500, 'g'), ingredient('carottes', 3, 'pièces'), ingredient('navets', 3, 'pièces'), ingredient('petits pois', 200, 'g'), ingredient('tomates concassées', 300, 'g')], ['Faire dorer les morceaux d’agneau.', 'Ajouter tomates et un verre d’eau puis mijoter 45 minutes.', 'Ajouter pommes de terre, carottes et navets.', 'Terminer avec les petits pois et cuire encore 30 minutes.']],
  ['salade-nicoise', 'Salade niçoise', 'Salade', 20, 25, 'Une salade complète au thon, œufs et légumes.', [ingredient('thon au naturel', 280, 'g'), ingredient('œufs', 4, 'pièces'), ingredient('tomates', 4, 'pièces'), ingredient('haricots verts', 300, 'g'), ingredient('olives noires', 80, 'g'), ingredient('salade verte', 1, 'pièce')], ['Cuire les œufs et les haricots verts.', 'Découper les tomates.', 'Répartir salade, légumes, thon, œufs et olives.', 'Assaisonner juste avant de servir.']],
  ['soupe-oignon', 'Soupe à l’oignon gratinée', 'Soupe', 15, 50, 'Une soupe chaude et économique avec ses tartines gratinées.', [ingredient('oignons', 700, 'g'), ingredient('bouillon de bœuf', 1, 'L'), ingredient('beurre', 30, 'g'), ingredient('farine', 1, 'c. à soupe'), ingredient('pain', 8, 'tranches'), ingredient('fromage râpé', 120, 'g')], ['Émincer puis faire fondre les oignons dans le beurre.', 'Ajouter la farine puis le bouillon et mijoter 25 minutes.', 'Verser dans des bols, ajouter pain et fromage.', 'Gratiner quelques minutes sous le gril.']],
  ['tarte-poireaux', 'Tarte aux poireaux', 'Tarte', 20, 50, 'Une tarte salée douce et pratique avec une salade.', [ingredient('pâte brisée', 1, 'pièce'), ingredient('poireaux', 4, 'pièces'), ingredient('œufs', 3, 'pièces'), ingredient('crème fraîche', 20, 'cl'), ingredient('fromage râpé', 80, 'g')], ['Émincer et faire fondre les poireaux.', 'Garnir un moule avec la pâte.', 'Mélanger œufs, crème, poireaux et fromage.', 'Verser sur la pâte et cuire 30 minutes à 190 °C.']]
];

function classicRecipes() {
  return definitions.map(([slug, title, category, prepMinutes, totalMinutes, description, ingredients, preparation], index) => ({
    id: `classic-${slug}`, title, category, prepMinutes, totalMinutes, description, ingredients, preparation,
    image: SPRITE, imagePosition: positions[index], imageSize: '500% auto', servings: 4,
    season: 'Toute saison', favorite: false, personal: false, source: 'Recette originale MealPilot', leftoverFriendly: totalMinutes > 30
  }));
}

module.exports = { classicRecipes, SPRITE };
